version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 28080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html